// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: product.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetProducts_GetProducts_FullMethodName = "/product.GetProducts/GetProducts"
)

// GetProductsClient is the client API for GetProducts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetProductsClient interface {
	GetProducts(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetPRoductResponse, error)
}

type getProductsClient struct {
	cc grpc.ClientConnInterface
}

func NewGetProductsClient(cc grpc.ClientConnInterface) GetProductsClient {
	return &getProductsClient{cc}
}

func (c *getProductsClient) GetProducts(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetPRoductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPRoductResponse)
	err := c.cc.Invoke(ctx, GetProducts_GetProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetProductsServer is the server API for GetProducts service.
// All implementations must embed UnimplementedGetProductsServer
// for forward compatibility.
type GetProductsServer interface {
	GetProducts(context.Context, *GetProductRequest) (*GetPRoductResponse, error)
	mustEmbedUnimplementedGetProductsServer()
}

// UnimplementedGetProductsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetProductsServer struct{}

func (UnimplementedGetProductsServer) GetProducts(context.Context, *GetProductRequest) (*GetPRoductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedGetProductsServer) mustEmbedUnimplementedGetProductsServer() {}
func (UnimplementedGetProductsServer) testEmbeddedByValue()                     {}

// UnsafeGetProductsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetProductsServer will
// result in compilation errors.
type UnsafeGetProductsServer interface {
	mustEmbedUnimplementedGetProductsServer()
}

func RegisterGetProductsServer(s grpc.ServiceRegistrar, srv GetProductsServer) {
	// If the following call pancis, it indicates UnimplementedGetProductsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetProducts_ServiceDesc, srv)
}

func _GetProducts_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetProductsServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetProducts_GetProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetProductsServer).GetProducts(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetProducts_ServiceDesc is the grpc.ServiceDesc for GetProducts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetProducts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.GetProducts",
	HandlerType: (*GetProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _GetProducts_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
