// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/showProduct.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShowProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowProductRequest) Reset() {
	*x = ShowProductRequest{}
	mi := &file_proto_showProduct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProductRequest) ProtoMessage() {}

func (x *ShowProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showProduct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProductRequest.ProtoReflect.Descriptor instead.
func (*ShowProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_showProduct_proto_rawDescGZIP(), []int{0}
}

func (x *ShowProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ShowProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowProductResponse) Reset() {
	*x = ShowProductResponse{}
	mi := &file_proto_showProduct_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProductResponse) ProtoMessage() {}

func (x *ShowProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showProduct_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProductResponse.ProtoReflect.Descriptor instead.
func (*ShowProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_showProduct_proto_rawDescGZIP(), []int{1}
}

func (x *ShowProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShowProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShowProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShowProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_proto_showProduct_proto protoreflect.FileDescriptor

const file_proto_showProduct_proto_rawDesc = "" +
	"\n" +
	"\x17proto/showProduct.proto\x12\vshowProduct\"3\n" +
	"\x12ShowProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"q\n" +
	"\x13ShowProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price2a\n" +
	"\vShowProduct\x12R\n" +
	"\vShowProduct\x12\x1f.showProduct.ShowProductRequest\x1a .showProduct.ShowProductResponse0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_showProduct_proto_rawDescOnce sync.Once
	file_proto_showProduct_proto_rawDescData []byte
)

func file_proto_showProduct_proto_rawDescGZIP() []byte {
	file_proto_showProduct_proto_rawDescOnce.Do(func() {
		file_proto_showProduct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_showProduct_proto_rawDesc), len(file_proto_showProduct_proto_rawDesc)))
	})
	return file_proto_showProduct_proto_rawDescData
}

var file_proto_showProduct_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_showProduct_proto_goTypes = []any{
	(*ShowProductRequest)(nil),  // 0: showProduct.ShowProductRequest
	(*ShowProductResponse)(nil), // 1: showProduct.ShowProductResponse
}
var file_proto_showProduct_proto_depIdxs = []int32{
	0, // 0: showProduct.ShowProduct.ShowProduct:input_type -> showProduct.ShowProductRequest
	1, // 1: showProduct.ShowProduct.ShowProduct:output_type -> showProduct.ShowProductResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_showProduct_proto_init() }
func file_proto_showProduct_proto_init() {
	if File_proto_showProduct_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_showProduct_proto_rawDesc), len(file_proto_showProduct_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_showProduct_proto_goTypes,
		DependencyIndexes: file_proto_showProduct_proto_depIdxs,
		MessageInfos:      file_proto_showProduct_proto_msgTypes,
	}.Build()
	File_proto_showProduct_proto = out.File
	file_proto_showProduct_proto_goTypes = nil
	file_proto_showProduct_proto_depIdxs = nil
}
