// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/proto/validateToken.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_internal_proto_validateToken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_validateToken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_validateToken_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_internal_proto_validateToken_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_validateToken_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_validateToken_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_internal_proto_validateToken_proto protoreflect.FileDescriptor

const file_internal_proto_validateToken_proto_rawDesc = "" +
	"\n" +
	"\"internal/proto/validateToken.proto\x12\rvalidateToken\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"-\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2k\n" +
	"\rValidateToken\x12Z\n" +
	"\rValidateToken\x12#.validateToken.ValidateTokenRequest\x1a$.validateToken.ValidateTokenResponseB\tZ\a./protob\x06proto3"

var (
	file_internal_proto_validateToken_proto_rawDescOnce sync.Once
	file_internal_proto_validateToken_proto_rawDescData []byte
)

func file_internal_proto_validateToken_proto_rawDescGZIP() []byte {
	file_internal_proto_validateToken_proto_rawDescOnce.Do(func() {
		file_internal_proto_validateToken_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_validateToken_proto_rawDesc), len(file_internal_proto_validateToken_proto_rawDesc)))
	})
	return file_internal_proto_validateToken_proto_rawDescData
}

var file_internal_proto_validateToken_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_validateToken_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),  // 0: validateToken.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 1: validateToken.ValidateTokenResponse
}
var file_internal_proto_validateToken_proto_depIdxs = []int32{
	0, // 0: validateToken.ValidateToken.ValidateToken:input_type -> validateToken.ValidateTokenRequest
	1, // 1: validateToken.ValidateToken.ValidateToken:output_type -> validateToken.ValidateTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_validateToken_proto_init() }
func file_internal_proto_validateToken_proto_init() {
	if File_internal_proto_validateToken_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_validateToken_proto_rawDesc), len(file_internal_proto_validateToken_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_validateToken_proto_goTypes,
		DependencyIndexes: file_internal_proto_validateToken_proto_depIdxs,
		MessageInfos:      file_internal_proto_validateToken_proto_msgTypes,
	}.Build()
	File_internal_proto_validateToken_proto = out.File
	file_internal_proto_validateToken_proto_goTypes = nil
	file_internal_proto_validateToken_proto_depIdxs = nil
}
